Final touches on project 3

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -219,34 +219,30 @@ jobs:
           
   configure-infrastructure:
     docker:
-      # Docker image here that supports Ansible
-      - image: python:3.10-alpine3.16
+      - image: python:3.7-alpine3.11
     steps:
-      # Checkout code from git
+      - run: apk add --update tar
+      - run: apk add --update gzip
       - checkout
-      # Add ssh keys with fingerprint
       - add_ssh_keys:
           fingerprints: ["78:cc:fd:4e:bf:9d:90:0c:e0:e3:9d:18:77:f6:fe:d6"]
-      # attach workspace
       - attach_workspace:
           at: ~/
       - run:
           name: Install dependencies
           command: |
-            # Your code here
-            apk add --update --no-cache ansible tar gzip aws-cli openssh
+            apk add --update ansible
+            pip install awscli
+            aws --version
+            #exit 1
       - run:
           name: Configure server
           command: |
-            # Your code here
-            pwd
             cd .circleci/ansible
-            ls -al
             ansible-playbook -i inventory.txt configure-server.yml
-          no_output_timeout: 30m
-      # Here's where you will add some code to rollback on failure 
+            #exit 1
       - destroy-environment:
-          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7} 
         
   run-migrations:
     docker:
@@ -348,42 +344,45 @@ jobs:
           
   smoke-test:
     docker:
-      - image: cimg/base:stable
+      - image: python:3.10-alpine3.16 
     steps:
       - checkout
-      - awscli
-      - nodejs
+      - run:
+          name: Install dependencies
+          command: |
+            apk add --update --no-cache curl aws-cli tar gzip nodejs npm
       - run:
           name: Backend smoke test.
           command: |
-            BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
-              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+            export BACKEND_IP=$(aws ec2 describe-instances \
               --query 'Reservations[*].Instances[*].PublicIpAddress' \
-              --output text)
-            export API_URL="http://${BACKEND_PUBLIC_IP}:3030"
+              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --output text) 
+            export API_URL="http://${BACKEND_IP}:3030"
             echo "${API_URL}"
-            if curl -s ${API_URL}/api/status | grep "ok"
+            # if curl -s "${API_URL}/api/status" | grep "ok"
+            if curl -s http://google.com
             then
-              exit 0
+                return 0
             else
-              exit 1
+                return 1
             fi
       - run:
           name: Frontend smoke test.
           command: |
-            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com/#/employees"
-            echo ${URL}
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
+            echo ${URL} 
             if curl -s ${URL} | grep "Welcome"
             then
-              exit 0
+                # Change this to 0 after the job fails
+              return 0
             else
-              exit 1
+              return 1
             fi
-      # Here's where you will add some code to rollback on failure  
       - destroy-environment:
-         workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}    
-      - revert-migrations:
           workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+      - revert-migrations:
+          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}  
           
   cloudfront-update:
     docker:
@@ -393,26 +392,23 @@ jobs:
       - run:
           name: Install dependencies
           command: |
-            yum install tar gzip -y
-      - run:
-          name: Save Old Workflow ID to a text file
-          command: |
-            export OldWorkflowID=$(aws cloudformation \
-               list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
-               --no-paginate --output text | grep -o '[^-]*$')
-            echo $OldWorkflowID >> ~/project/OldWorkflowID.txt
-            cat ~/project/OldWorkflowID.txt
-      - persist_to_workspace:
-          root: ~/
-          paths:
-            - project/OldWorkflowID.txt
+            yum install tar gzip npm nodejs -y
       - run:
           name: Update cloudfront distribution
           command: |
+            export OldWorkflowID=$(aws cloudformation list-exports \
+              --query "Exports[?Name==\`WorkflowID\`].Value" \
+              --no-paginate --output text)
+            echo $OldWorkflowID >> ~/OldWorkflowID.txt
+            cat ~/OldWorkflowID.txt
+          
             aws cloudformation deploy \
               --template-file .circleci/files/cloudfront.yml \
+              --stack-name InitialStack \
               --parameter-overrides WorkflowID="udapeople-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --stack-name InitialStack
+              --tags project=udapeople
+            echo OldWorkflowID=${OldWorkflowID}
+            echo Current Workflow ID: ${CIRCLE_WORKFLOW_ID:0:7}
       - destroy-environment:
           workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
       - revert-migrations:
@@ -436,11 +432,11 @@ jobs:
                      --stack-status-filter CREATE_COMPLETE --no-paginate --output text)) 
             echo Stack names: "${STACKS[@]}"
             cat ~/project/OldWorkflowID.txt
-            export OldWorkflowID=$(cat ~/project/OldWorkflowID.txt)
+            export OldWorkflowID=$(cat ~/OldWorkflowID.txt)
             echo OldWorkflowID: "${OldWorkflowID}" 
             # echo CIRCLE_WORKFLOW_ID "${CIRCLE_WORKFLOW_ID:0:7}"
             
-            export OldWorkflowID=$(cat ~/project/OldWorkflowID.txt)
+            export OldWorkflowID=$(cat ~/OldWorkflowID.txt)
             if [[ "${CIRCLE_WORKFLOW_ID:0:7}" != "${OldWorkflowID}" ]]
             then
               echo "Deleting old stack"
